model: sonnet

# Disable commits pending support for signatures.
# https://github.com/Aider-AI/aider/issues/1600
auto-commits: false

# Use global ~/.config/git/ignore instead of updating every repo.
gitignore: false

lint-cmd:
  - "python: ruff check --fix && ruff format"

auto-lint: true

test-cmd: "uv run pytest -vv"

auto-test: true
