# Target Python 3.13+ for maximum modernization
target-version = "py313"

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
  "ALL",
]

ignore = [
  "ANN401",  # typing.Any
  "C90",     # Cyclomatic complexity
  "D",       # pydocstyle (disable docstring rules)
  "PLR09",   # "Too many" branches, arguments, etc.
  "S603",    # subprocess output
  "S607",    # subprocess using path
  "T201",    # print()
]
