# Target Python 3.14+ for maximum modernization
target-version = "py314"

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
  "ALL",
]

ignore = [
  "ANN401",  # typing.Any
  "C90",     # Cyclomatic complexity
  "D",       # pydocstyle (disable docstring rules)
  "PLR09",   # "Too many" branches, arguments, etc.
  "S603",    # subprocess output
  "S607",    # subprocess using path
  "T201",    # print()
  "RUF001",  # ambiguous Unicode character in string
  "RUF002",  # ambiguous Unicode character in docstring
  "RUF003",  # ambiguous Unicode character in comment
]
