(custom-set-variables
 '(bbdb-gui nil)
 '(gnus-treat-body-boundary nil)
 '(gnus-treat-newsgroups-picon nil)
 '(message-required-mail-headers (quote (From Date (optional . In-Reply-To) Message-ID Lines (optional . User-Agent))))
 '(bbdb-complete-name-allow-cycling t)
 '(gnuserv-program (concat exec-directory "/gnuserv"))
 '(canlock-password "c5050b0b84d19f7fc1b4a113f2fbbab44c219402")
 '(bbdb-time-display-format "%Y-%m-%d")
 '(gnus-treat-mail-picon nil)
 '(gnus-treat-display-xface nil)
 '(gnus-treat-from-picon nil))
(custom-set-faces
 '(info-node ((t (:foreground "darkblue"))))
 '(gnus-header-newsgroups-face ((((class color) (background light)) (:foreground "MidnightBlue"))))
 '(gnus-group-mail-3-face ((((class color) (background light)) nil)))
 '(gnus-summary-low-unread-face ((t (:foreground "grey18"))))
 '(gnus-summary-low-ticked-face ((((class color) (background light)) (:foreground "firebrick"))))
 '(gnus-group-news-3-face ((((class color) (background light)) nil)))
 '(gnus-header-content-face ((((class color) (background light)) (:foreground "indianred4"))))
 '(gnus-group-mail-3-empty-face ((((class color) (background light)) nil)))
 '(gnus-cite-face-4 ((((class color) (background light)) (:foreground "slateblue3"))))
 '(message-cited-text-face ((((class color) (background light)) (:foreground "indianred4"))))
 '(gnus-group-news-5-face ((((class color) (background light)) nil)))
 '(gnus-signature-face ((((type x)) (:foreground "grey50"))))
 '(gnus-group-news-4-face ((((class color) (background light)) nil)))
 '(gnus-summary-low-ancient-face ((((class color) (background light)) (:foreground "RoyalBlue"))))
 '(gnus-group-news-6-face ((((class color) (background light)) nil)))
 '(gnus-summary-low-read-face ((((class color) (background light)) (:foreground "DarkGreen")))))

(setq minibuffer-max-depth nil)
