format = "$username$hostname$directory$git_commit$git_branch$git_status$python$cmd_duration$jobs$status$character"
add_newline = false

[username]
format = "[$user]($style) "

[hostname]
format = "[$hostname]($style) "
ssh_only = true

[directory]
style = "black bold"
before_repo_root_style = "black bold dimmed"
repo_root_style = "$style"
read_only = ""
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
symbol = ""
style = "bold cyan"

[git_commit]
format = "([$hash$tag]($style) )"
style = "cyan"
only_detached = false
tag_disabled = false
tag_symbol = " 󰓼 "

[git_status]
format = '([$ahead_behind$all_status]($style) )'
ahead = '  ${count}'
diverged = '⇕  ${ahead_count}  ${behind_count}'
behind = '  ${count}'
conflicted = ' [ ](red)'
untracked = " 󱀶 ($count)"
stashed = " 󰘓 "
modified = " 󰏫 ($count)"
staged = "  ($count)"
renamed = " 󰬳 ($count)"
deleted = "  ($count)"
style = "cyan"

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
detect_files = []
detect_extensions = []

[cmd_duration]
format = "[ $duration]($style) "
style = "black dimmed"

[status]
format = "[ $symbol$status]($style) "
symbol = ""
disabled = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
