format = "$username$hostname$directory$git_branch$git_status$python$kubernetes$cmd_duration$jobs$status$character"
add_newline = false

[username]
format = "[$user]($style) "

[hostname]
format = "[$hostname]($style) "
ssh_only = true

[directory]
style = "black bold"
before_repo_root_style = "black bold dimmed"
repo_root_style = "$style"
read_only = ""
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
symbol = ""

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
detect_files = []
detect_extensions = []

[kubernetes]
format = '[$symbol$context]($style) '
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "black dimmed"

[status]
format = "[$symbol$status]($style) "
symbol = ""
disabled = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
