# Copyright © 2024 Michael Shields
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[window]
dimensions = { columns = 132, lines = 100 }

[font]
# This is too bold for some reason.
normal = { family = "Andale Mono", style = "Regular" }
size = 12

[colors]
cursor = { text = "#ffffff", cursor = "#b22222" }  # firebrick

[colors.primary]
foreground = "#000000"
background = "#ffffff"

[bell]
duration = 250
