(load "~/.emacs.d/package-repos.el")
(package-initialize)
(package-refresh-contents nil)

(package-install 'aggressive-indent)
(package-install 'company)
(package-install 'company-go)
(package-install 'flx-ido)
(package-install 'flycheck)
(package-install 'go-eldoc)
(package-install 'go-mode)
(package-install 'magit)
(package-install 'markdown-mode)
(package-install 'projectile)
(package-install 'smartparens)
(package-install 'yasnippet)
